### ISSUE TITLE
Create Network

### ISSUE THREAD

**Issue by JordanXtern** [Twingate-Labs/Twingate-CLI#2]
The Python CLI currently lacks the necessary API for creating networks, while the JavaScript version includes this functionality. This missing feature creates a disparity between the two versions and hinders Python users from efficiently managing networks through the command line and automation scripts.

**Comment by brendan-tg** [comment]
hi @JordanXtern,

thanks for the feedback! We will add it.

**Comment by brendan-tg** [comment]
added!
